### ISSUE TITLE
Bug ( ? ) address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied

### ISSUE THREAD

**Issue by x9t9** [cmderdev/cmder#1214]
Ok, so this might be a difficult issue to reproduce , because : 

1.  I have installed and used `CMDER` on a few machines ( Love it . Great job ) , and it has appeared only in one of them ( all machines  win7 sp1 ).
2. I only noticed it provoking a very specific git operation ( migration of SVN to git using [SVN2GIT ](https://github.com/nirvdrum/svn2git) which is a ruby gem ) 
3. As noted above, this operation requires installation of several components - all of which could potentially be part of the problem. ( Git, SVN client , SVN Server [svnserve.exe ] , Ruby, Gem )

### Synopsis

When trying to migrate an SVN repo into GIT with [SVN2GIT ](https://github.com/nirvdrum/svn2git) using `CMDER` ( and **only** from `CMDER`  ) ,  I get the following error :  
`child_info_fork::abort: dll loaded to different address`

or

 `address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied`

### Full Error messages :  

  ```
    2 [main] perl 3260 child_info_fork::abort: address space       2 [main] perl 3260 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
      2 [main] perl 2940 child_info_fork::abort: address       2 [main] perl 2940 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
      1 [main] perl 2964 child_info_fork::abort: address space needed       1 [main] perl 2964 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
by 'msys-apr-1-0.dll' (0xA70000) is already occupied
      2 [main] perl 3824 child_info_fork::abort: address space needed by       2 [main] perl 3824 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
'msys-apr-1-0.dll' (0xA70000) is already occupied
      2 [main] perl 3336 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll'       2 [main] perl 3336 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
(0xA70000) is already occupied
       61 [main] perl 3904 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
   61 [main] perl 3904 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied

      2 [main] perl 1912 child_info_fork::abort: address space       2 [main] perl 1912 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
      2 [main] perl 2720 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll'       2 [main] perl 2720 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
(0xA70000) is already occupied
      2 [main] perl 3520 child_info_fork::abort: address space       2 [main] perl 3520 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
      2 [main] perl 3616 child_info_fork::abort: address space needed       2 [main] perl 3616 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
by 'msys-apr-1-0.dll' (0xA70000) is already occupied
    150 [main] perl 548 child_info_fork::abort: address space needed     150 [main] perl 548 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0xA70000) is already occupied
by 'msys-apr-1-0.dll' (0xA70000) is already .... 
```

It goes on until interrupt by `CTRl+C`
```
 C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:443:in `join': Interrupt
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:443:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:443:in `block in run_command'

        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:410:in `popen'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:410:in `run_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:224:in `clone!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/svn2git-2.4.0/lib/svn2git/migration.rb:34:in `run!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/svn2git-2.4.0/bin/svn2git:27:in `<top (required)>'
        from C:/Ruby23-x64/bin/svn2git:22:in `load'
        from C:/Ruby23-x64/bin/svn2git:22:in `<main>'
Terminate batch job (Y/N)? y
```

### Error reproducing : 

Error is provoked by the command : 
`svn2git svn://127.0.0.1/repo --username svnUserName --authors authors.txt --notags --nobranches --notrunk`

But actually any `git svn` command ( or fetch ) that I tried produced similar errors on my machine.

### Apparent Culprit  :  
After some googling , it [appears to be a problem of cygwin](http://stackoverflow.com/questions/11107155/how-to-fix-address-space-is-already-occupied-error-on-fetch-commit)

Another win shell replacement ( babun) was one of the hits when searching for the error message . ( https://github.com/babun/babun/issues/477 ).

After reading [here ](https://cygwin.com/ml/cygwin/2012-02/msg00662.html) and also [here ](https://cygwin.com/faq-nochunks.html#faq.using.bloda) I do suspect that this is the mentioned problem because the affected machine has in fact `COMODO` installed, as well as `CATALYST` ( both on the cygwin list of potential trouble makers ) . However - disabling them does not help .

### Is this a bug ?
well, apparently it is a somewhat unrelated bug / issue of cygwin ( or git , or both ) - but since I used the embedded CMDER git - and in view of the fact that The same command, same machine, will **NOT** fail under `powershell` ( github for win gitshell ) or normal `CMD` - than it might as well be reported as an issue here ....

**Comment by warpsprung** [comment]
What solved the problem for me was searching for all versions of "msys-apr-1-0.dll" and deleting the oldest ones like the one in my cmder installation. So I would suggest an update of the msys dll's in ConEmu and/or Cmder.

**Comment by warpsprung** [comment]
Trying to run the "git svn clone" command doesn't work on my machine within Cmder/ConEmu. In a CMD shell outside of Cmder the command succeeds in at least 1 out of roughly 5 times.

**Comment by gogomako** [comment]
It also happened to my git-svn repository in windows 7 CMD shell, even on the not embedded CMD. I triggered by executing `rbt post` which rbt is a code reviewing tool [RBT tool](https://github.com/reviewboard/rbtools).
These are my error messages.
```
0 [main] perl 7312 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 6632 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 12328 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 12924 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 1240 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      1 [main] perl 11012 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 7280 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 11528 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 9504 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 7712 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 12108 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 8088 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 4388 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 10704 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 7264 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 12356 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 12536 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 3320 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 11676 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 12708 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 5592 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 11756 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 11088 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 1552 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 3536 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 10744 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 12080 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 9780 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 13104 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 12936 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 7388 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 13120 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 9316 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 10884 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 10096 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 10208 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 12896 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 12096 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 10052 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 9444 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 10252 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 3660 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 8788 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 8700 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 3428 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 7844 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 13052 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 9240 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 8856 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 6684 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 8540 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 11340 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 10028 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 8736 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 11540 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
      0 [main] perl 8000 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000)
 is already occupied
      0 [main] perl 11424 child_info_fork::abort: address space needed by 'msys-apr-1-0.dll' (0x29E0000
) is already occupied
CRITICAL: This clone has no configured remotes.
```
